woman = ("Brígida Manso Acosta",
"Susana Llano Pujol",
"Andrea Pozo Mate",
"Ileana Altrina Aller",
"Eulalia Jimenez Canals",
"Ángeles Cobo Pla",
"Ascensión Coll Carballo",
"Obdulia Elorza Haro",
"Brígida Bermudez Amores",
"Calixta Arévalo Pujadas",
"Cándida Coello Sevillano",
"Martirio Priego Hurtado",
"Eli Moya Palomar",
"Juliana Lomache Luís",
"Consuela María Vera Maldonado",
"Eligia Lucena Villanueva",
"Palmira Herranz Morán",
"Rosalina Folch Dianes",
"Candelaria Izquierdo Zurdo",
"Dafne Tolosa Pains",
"Loreto Mur Lum",
"Gertrudis Torrecilla Valverde",
"Narcisa Falcón Albero",
"Rosario Carmen Tomas Anaya",
"Dionisia Ali Valdés Báez",
"Eva Gelion Blasco Jiménez",
"Elena Dulce Cid Sabater",
"Gala Dueñas Núñez",
"Fanny Flor Milla Gámez",
"Teresita Navas Polisa",
"María Manuela Melero Mayol",
"Gema Viña Marín",
"Vilma Redondo Bilbao",
"Gracia Molins Requena",
"Valentina Pastor Crud",
"Valentina Azucena Guerrero Sola",
"José Calderón Río",
"Marita Alfonso Castell",
"Esmeralda Solís Amapi",
"Violeta Tamara Castillo Gimenez",
"María Cristina Milagros Ricart",
"Isabel Marco Blasco",
"Miriam Montaña Ortuño",
"Cayetana Viviana Velázquez Almazán",
"Hortensia Herrera Díaz",
"Paz Parejo Olivera",
"Albina Zorrilla Domingo",
"Paz Español Catalán",
"Custodia Luz Peñas",
"Bárbara Criado Lorem")

men = ("Atilio Torralba Ortega",
"Albert Flavio Linares Solsona",
"Martín Moraleda Botella",
"Fabio Asensio Sosa",
"Alonso Sureda Almeida",
"Juan Francisco Dalmau Elías",
"Natanael Leiva Cervera",
"Juan Antonio Cózar",
"Segismundo Sedano Sidan",
"Nando Ortiz Cárdenas",
"Segismundo Pozo Cueva",
"Andrés Felipe Cano",
"Cornelio Pinto Viña",
"Osvaldo Humberto Ojeda Valle",
"Abilio Vara López",
"José Ángel Badía Bellido",
"Vicente Blanca Solsona",
"Elías Miguel Padilla",
"Poncio Guillen Lucena",
"Angelino Alcolea Izquierdo",
"Cruz Alcázar Mínguez",
"Juan Antonio Segarra Maza",
"Leonel Navarro Tamayo",
"Augusto Marcos Noguera",
"Arturo Fortunato Soler Leiva",
"José Luis Bárcena",
"Jose Ignacio Bernad",
"Alfonso Marí Sevilla",
"Teobaldo Domingo Morán",
"Cornelio Cuole Díez",
"Abel Llanos Álamo",
"Nilo Parra Atahualpa",
"Feliciano Casal Murcia",
"Adrián Pol Ariño Magro",
"Luis Miguel Aragonés Galan",
"Iván Sáenz Cortes",
"Ismael Raya Bilbao",
"Danilo Granados Ordóñez",
"Chus Roura Limache",
"Sandalio Antón Lloret",
"Godofredo Carrera Alemany",
"Valentín Nogueira Olivé",
"Patricio Manjón Osuna",
"Adrián Vila Alemany",
"Aarón Benítez Diez",
"Américo Valverde Guardia",
"Miguel Ángel Pineda",
"Santos Tena Paredes",
"Lázaro Salcedo Carrasco",
"Francisco Jose Coronado Torre")

proveedores = ("Rapidiagnostics S.A.C.",
"Plenno Peru",
"Mased Representaciones S.A.C.",
"Ipc Associates",
"Dicar Logistic, Almacén Con Bpa",
"Centro Médico Amc",
"Amelife Llc",
"A. Tarrillo Barba S.A.",
"Dt Comunity E.i.r.l.",
"Drogueria Mym S.A.C",
"Corporación Castillo",
"Audiomax S.A.C",
"Medisonic S.A.C.",
"Laboratorio Cemedic S.A.C",
"Jc Medical Supplies S.A.C",
"Jampar Multiplest Internacional",
"Ghs Peru",
"Farmacia Universal",
"3M Peru S.A.",
"Advantage Medical Sociedad Anonima Cerrada")